# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "chef/ubuntu-14.04"
  config.vm.network "forwarded_port", guest: 80, host: 8185

  config.vm.provider "virtualbox" do |vb|
     vb.gui = false
     vb.memory = "1024"
  end


#  config.vm.provision "puppet"
# http://docs.vagrantup.com/v2/provisioning/puppet_apply.html

  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get -y update
    sudo apt-get -y install git
    sudo apt-get -y install puppet
    sudo apt-get -y install librarian-puppet
    sudo apt-get -y install apache2
    sudo rm -rf /var/www/html
    sudo cp -a /vagrant/client-facing-site/ /var/www/
    sudo mv /var/www/client-facing-site/* /var/www/
  SHELL
end
